### ISSUE TITLE
Introduce support for OAuth resource indicators

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#381]
https://tools.ietf.org/html/rfc8707

Which is basically a standardized way to request an audience for the issued tokens

**Comment by vokac** [comment]
Would it be possible to increase priority to this item, because not to require workarounds in the clients and their configuration, e.g. https://github.com/indigo-dc/oidc-agent/issues/310

**Comment by rmiccoli** [comment]
Same as #841

**Comment by vokac** [comment]
Is #429 also resolved by this update?

**Comment by federicaagostini** [comment]
Hi, point 1 (i.e. a `typ` claim must be present in the token header) is not solved, while point 2 is solved with wlcg profile, where when no audience is requested a default value is returned in the JWT. 

This issue (resource indicator request according with [RFC8707](https://tools.ietf.org/html/rfc8707)) is only about the way one has to request for an audience - through a `resource` parameter, which must be an absolute URI, etc.
